apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/open-telemetry/opentelemetry-helm-charts.git
    path: charts/opentelemetry-collector
    targetRevision: 0.110.7 # Use a specific chart version
    helm:
      values: |
        mode: deployment
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
          exporters:
            logging:
              loglevel: debug
            jaeger:
              endpoint: jaeger-collector.monitoring.svc.cluster.local:14250
              tls:
                insecure: true
            prometheus:
              endpoint: 0.0.0.0:8889
          service:
            pipelines:
              traces:
                receivers: [otlp]
                exporters: [jaeger, logging]
              metrics:
                receivers: [otlp]
                exporters: [prometheus, logging]
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true